In [58]:
import numpy as np

Creating Arrays

In [59]:
a=[1,2,3,4,55,5,4]

In [60]:
arr1=np.array(a)
arr1

array([ 1,  2,  3,  4, 55,  5,  4])

In [5]:
type(arr1)

numpy.ndarray

In [6]:
ar1=np.arange(10)
ar1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr2=np.arange(10,20,2.4)
arr2

array([10. , 12.4, 14.8, 17.2, 19.6])

In [8]:
arr3=np.arange(1,10).reshape(3,3)
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
arr3.size

9

In [10]:
arr3.ndim #it shows 2-D or 3-D

2

In [11]:
arr3.max()

9

In [12]:
arr3.min()

1

In [13]:
arr3.sum()

45

In [14]:
arr3.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr3.prod()

362880

In [16]:
arr3.mean()

5.0

In [17]:
arr3.real

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
arr3.repeat

<function ndarray.repeat>

In [19]:
arr3.sort()

In [20]:
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
arr3.squeeze()

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
arr3.diagonal()

array([1, 5, 9])

In [23]:
arr3.view()

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
np.arange(1,9, dtype=np.float64).reshape(2,2,2)

array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]]])

In [25]:
mat1=np.arange(1,21).reshape(4,5)
mat1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [26]:
mat1**3

array([[   1,    8,   27,   64,  125],
       [ 216,  343,  512,  729, 1000],
       [1331, 1728, 2197, 2744, 3375],
       [4096, 4913, 5832, 6859, 8000]], dtype=int32)

In [27]:
mat2=mat1.flatten()
mat2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [28]:
for i in mat2:
    if i%2==0:
        print(i)
        

2
4
6
8
10
12
14
16
18
20


In [29]:
b_arr=mat1%2==0
b_arr

array([[False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True]])

In [30]:
mat1[b_arr]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [31]:
mat1[mat1%5==0]

array([ 5, 10, 15, 20])

In [32]:
mat1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [33]:
mat1[1,3]

9

In [34]:
mat1[2,4]

15

In [35]:
mat1[1:3,3]

array([ 9, 14])

In [36]:
mat1[1,1:4]

array([7, 8, 9])

In [37]:
mat1[0:2,1:5]


array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10]])

In [38]:
ar2=np.random.randint(1,10,(10,10))
ar2

array([[3, 7, 6, 9, 2, 5, 3, 8, 5, 8],
       [7, 3, 3, 2, 1, 1, 3, 7, 8, 9],
       [7, 8, 3, 3, 8, 9, 7, 9, 2, 9],
       [9, 9, 7, 7, 3, 4, 2, 1, 3, 5],
       [5, 3, 2, 5, 2, 6, 2, 7, 8, 7],
       [1, 8, 5, 5, 9, 1, 5, 5, 3, 4],
       [9, 4, 8, 7, 4, 2, 3, 2, 3, 6],
       [5, 2, 9, 1, 5, 6, 8, 8, 3, 1],
       [3, 2, 6, 6, 5, 9, 6, 7, 8, 1],
       [7, 3, 7, 5, 8, 5, 8, 1, 8, 7]])

In [39]:
np.random.random((5,5))

array([[0.0158364 , 0.16542281, 0.77949485, 0.58713344, 0.36958236],
       [0.53720676, 0.31971552, 0.69685266, 0.35061868, 0.93248759],
       [0.04098564, 0.32370425, 0.47330157, 0.60946288, 0.44264734],
       [0.2360564 , 0.13133317, 0.07982436, 0.81982587, 0.39049039],
       [0.49745063, 0.96425553, 0.44926566, 0.16474997, 0.87809333]])

In [40]:
mat2=np.arange(1,7).reshape(3,2)
mat2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [41]:
mat3=np.arange(1,7).reshape(2,3)
mat3

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
mat2@mat3

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [43]:
mat4=np.arange(1,5).reshape(2,2)
mat4

array([[1, 2],
       [3, 4]])

In [44]:
np.vstack((mat2,mat4))

array([[1, 2],
       [3, 4],
       [5, 6],
       [1, 2],
       [3, 4]])

In [45]:
np.hstack((mat3,mat4))

array([[1, 2, 3, 1, 2],
       [4, 5, 6, 3, 4]])

In [46]:
# Horrizently split will seprate the columns.
np.hsplit(mat2,2)

[array([[1],
        [3],
        [5]]),
 array([[2],
        [4],
        [6]])]

In [47]:
mat2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [48]:
mat2.transpose()

array([[1, 3, 5],
       [2, 4, 6]])

In [49]:
mat2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [50]:
# sum along the diagnils.
mat2.trace()


5

In [51]:
mat4

array([[1, 2],
       [3, 4]])

In [52]:
mat5=np.arange(5,9).reshape(2,2)
mat5

array([[5, 6],
       [7, 8]])

In [53]:
mat4*mat5

array([[ 5, 12],
       [21, 32]])

In [54]:
mat4 @ mat5

array([[19, 22],
       [43, 50]])

In [55]:
mat4.dot(mat5)

array([[19, 22],
       [43, 50]])

In [56]:
np.eye(5, dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [57]:
mat5 @ np.eye(2)

array([[5., 6.],
       [7., 8.]])